# main text of home
name: κριβ
bio: what should have been left alone in 2002

# twitter summary info
description: what should have been left alone in 2002

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/zetapsi.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
resume-url: https://google.com/?q=my+resume

url: https://ir7777.github.io/KRIB/
# your url: http://USERNAME.github.io  -- THIS SHOULD BE WHERE YOUR SITE IS HOSTED!!!

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
#disqus:
#  shortname: mydisqus # enter this from your disqus account
#  categories: [blog] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
# twitter: mytwitter
# google: mygoogle
instagram: iridium7777
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: ir7777
# gitlab: mygitlab
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
email: iridium7777@mac.com

authors:
    orest:
        name: orest
        bio: co-founder, cto & ceo of κριβ
        external-image: false
        picture: assets/images/profile.jpg
        #twitter: johndoe
  

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: false

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: ["travis.sh", "Rakefile", "README.md", "Gemfile", "Gemfile.lock", "FAQ.md"]
